config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),

]

portfolio/urls.py
#  hello/urls.py

from django.shortcuts import render
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('about', views.about_page_view, name="about"),
    path('apresentacao', views.apresentacao_page_view, name="apresentacao"),
    path('competencias', views.competencias_page_view, name="competencias"),
    path('foramacao', views.formacao_page_view, name="formacao"),
    path('projetos', views.projetos_page_view, name="projetos"),
    path('posts', views.posts_page_view, name="posts"),
    path('criar_post', views.criar_post_page_view, name="criar_post"),
    path('editar_post/<int:post_id>', views.editar_post_page_view, name="editar_post"),
    path('web', views.web_page_view, name="web"),
    path('criar_cadeira', views.criar_cadeira_page_view, name="criar_cadeira"),
    path('criar_comentario/<int:post_id>/comentario', views.criar_comentario_page_view, name='criar_comentario'),
    path('login', views.login_page_view, name='login'),
    path('logout', views.logout_page_view, name='logout'),
    path('criar_tfc', views.criar_tfc_page_view, name='criar_tfc'),
    path('javascript_testes', views.javascript_tests_page_view, name='javascript_testes'),
    path('colors', views.colors_page_view, name='colors'),
    path('input_color', views.input_color_page_view, name='input_color'),
    path('ipma', views.ipma_page_view, name='ipma'),
    path('contact', views.contact_page_view, name='contact'),










]

portfolio/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from django import forms

# Para o campo não ser obrigatório mete-se ", blank= True"

class Pessoa(models.Model):
    nome = models.TextField(max_length=80)
    linkin = models.URLField(blank=True)

    def __str__(self):
        return self.nome


class Post(models.Model):

    titulo = models.CharField(max_length=60)
    descricao = models.TextField()
    criacao = models.DateTimeField(auto_now_add=True)
    autor = models.CharField(max_length=20)

    def __str__(self):
        return self.titulo+" - "+self.autor


class Comentario(models.Model):
    post = models.ForeignKey(Post, related_name="coments", on_delete=models.CASCADE)
    autor = models.CharField(max_length=20)
    conteudo = models.TextField()
    criacao_data = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return '%s - %s' % (self.post.titulo, self.autor)



class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=50)
    pontuacao = models.IntegerField()
    criacao = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nome+" : "+str(self.pontuacao)


class Linguagem(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome


class Professor(models.Model):
    nome = models.CharField(max_length=30)
    linkedin = models.CharField(max_length=150, blank=True)
    universidade = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return self.nome


class Projeto(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome


class Cadeira(models.Model):
    nome = models.CharField(max_length=50)
    ano = models.IntegerField()
    semestre = models.IntegerField()
    nota = models.IntegerField()
    ects = models.IntegerField(default=0)
    ranking = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(5)])
    linguagens = models.ManyToManyField(Linguagem, blank=True)
    professor_teorica = models.ForeignKey(Professor, on_delete=models.CASCADE)
    professor_pratica = models.ManyToManyField(Professor, related_name='professor_pratica')
    projetos = models.ManyToManyField(Projeto, blank=True)

    def __str__(self):
        return f"{self.nome} - Professor: {self.professor_teorica}"

class Tfc_autor(models.Model):
    nome = models.TextField(max_length=80)
    linkin = models.URLField(blank=True)

    def __str__(self):
        return self.nome


class Tfc_orientador(models.Model):
    nome = models.TextField(max_length=80)
    linkin = models.URLField(blank=True)

    def __str__(self):
        return self.nome



class Tfc_terceiros(models.Model):
    autores = models.ManyToManyField(Tfc_autor, related_name="autores")
    orientadores = models.ManyToManyField(Tfc_orientador, related_name="orientadores")
    ano = models.IntegerField()
    titulo = models.CharField(max_length=50)
    resumo = models.TextField(max_length=1000)
    github_link = models.URLField()

    def __str__(self):

        return f"{self.titulo} - {list((self.autores.all()))}"

portfolio/forms.py
from django.forms import ModelForm

from .models import *


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['comentarios']


class CadeiraForm(ModelForm):
    class Meta:
        model = Cadeira
        fields = '__all__'


class ComentarioFrom(ModelForm):
    class Meta:
        model = Comentario
        fields = ('autor', 'conteudo')


class TfcForm(ModelForm):
        class Meta:
            model = Tfc_terceiros
            fields = '__all__'

portfolio/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import *
from .models import *
# Create your views here.
from .quizz_functs import pontuacao_quizz


def javascript_tests_page_view(request):
    return render(request, 'testes_js/javascript_testes.html')


def colors_page_view(req):
    return render(req, 'testes_js/colors.html')


def input_color_page_view(req):
    return render(req, 'testes_js/input_color.html')


def ipma_page_view(req):
    return render(req, 'testes_js/IPMA.html')


def home_page_view(request):
    return render(request, 'portfolio/home.html')


def contact_page_view(req):

    if req.method == "POST":
        name = req.method["name"]
        email = req.method["email"]
        message = req.method["message"]


        return render(req, 'portfolio/contact.html')
    else:
        return render(req, 'portfolio/contact.html')


def layout_page_view(request):
    return render(request, 'portfolio/layout.html')


def about_page_view(request):
    context = {'cadeiras': sorted(Cadeira.objects.all(), key=lambda cadeira: cadeira.ano and cadeira.semestre)}
    return render(request, 'portfolio/about.html', context)


def apresentacao_page_view(request):
    return render(request, 'portfolio/apresentacao.html')


def competencias_page_view(request):
    return render(request, 'portfolio/competencias.html')


def formacao_page_view(request):
    return render(request, 'portfolio')


def projetos_page_view(request):
    context = {'tfcs' : Tfc_terceiros.objects.all()}

    return render(request, 'portfolio/projetos.html', context)


def posts_page_view(request):
    context = {'posts': sorted(Post.objects.all(), key=lambda objeto:objeto.criacao, reverse=True)}
    return render(request, 'blog/posts.html', context)


def criar_post_page_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/posts')

    context = {'form':form}

    return render(request, 'blog/criar_post.html', context)


def editar_post_page_view(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/posts')

    context = {'form': form, 'post_id': post_id}

    return render(request, 'blog/editar_post.html', context)


def criar_comentario_page_view(request, post_id):
    form = ComentarioFrom(request.POST or None)
    post = Post.objects.get(pk=post_id)

    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.post = post
        new_comment.save()

        return HttpResponseRedirect('/posts')

    context = {'form': form, 'post_id': post_id}
    return render(request, 'blog/criar_comentario.html', context)


def web_page_view(request):
    if request.method == 'POST':
        name = request.POST['nome']+" "+request.POST['apelido']
        pontuacao = pontuacao_quizz(request)

        r = PontuacaoQuizz(nome = name, pontuacao=pontuacao)
        r.save()

    return render(request, 'web/web.html')


@login_required()
def criar_cadeira_page_view(request):
    form = CadeiraForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/about')

    context = {'form':form}

    return render(request, 'portfolio/criar_cadeira.html', context)


def login_page_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(
            request,
            username=username,
            password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')

        else:
            return render(request, 'authenticate/login.html', {
                'message': 'Credenciais invalidas.'
            })

    return render(request, 'authenticate/login.html')


def logout_page_view(request):
    logout(request)

    return render(request, 'portfolio/home.html', {
                'message': 'Foi desconetado.'
            })


def criar_tfc_page_view(request):
    form = TfcForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/projetos')

    context = {'form':form}

    return render(request, 'portfolio/criar_tfc.html', context)

portfolio/templates/portfolio/about.html
{%  extends 'portfolio/layout.html' %}

{% block estilos %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/styles_about.css' %}" type="text/css">
{% endblock %}

{% block main %}
    <div class="licenciatura">
        <div class="info-side">
            <br>
            <br>
            <br>

            <h1>Licenciatura</h1>
            <h3 class="uni_name">Universidade Lusófona de Humanidades e Tecnologias</h3>
            <br>
        </div>

        {% if request.user.is_authenticated %}
            <div class="btn_div">
                <a href="{% url 'portfolio:criar_cadeira' %}" class="btn">+ Nova Cadeira</a>
            </div>
        {% endif %}


        <div class="cards-side">
            <div class="cards-conteiner">
            {% for cadeira in cadeiras %}
                <div class="card">
                    <h2>{{ cadeira.nome}}</h2>
                    <br>
                    <p>{{ cadeira.ano}}º Ano - {{ cadeira.semestre }}º Semestre</p>
                    <br>
                    <p>Nota: {{ cadeira.nota}}</p>
                    <br>
                    <p>ECTS: {{ cadeira.ects }}</p>
                    <br>
                    {% if cadeira.ranking == 1 %}
                        <p>Ranking {{ cadeira.ranking }}/5 ⭐</p>
                    {% endif %}
                    {% if cadeira.ranking == 2 %}
                        <p>Ranking {{ cadeira.ranking }}/5 ⭐⭐</p>
                    {% endif %}
                    {% if cadeira.ranking == 3 %}
                        <p>Ranking {{ cadeira.ranking }}/5 ⭐⭐⭐</p>
                    {% endif %}
                    {% if cadeira.ranking == 4 %}
                        <p>Ranking {{ cadeira.ranking }}/5 ⭐⭐⭐⭐</p>
                    {% endif %}
                    {% if cadeira.ranking == 5 %}
                        <p>Ranking {{ cadeira.ranking }}/5 ⭐⭐⭐⭐⭐</p>
                    {% endif %}
                    <br>
                    <div class="professors_grid">
                        <div class="professor">
                            <h3>Teóricas</h3>
                            <p>{{ cadeira.professor_teorica}}</p>
                            <a href="{{ cadeira.professor_teorica.linkedin }}" target="_blank" >Linkedin</a>
                            <a href="{{ cadeira.professor_teorica.universidade }}" target="_blank">Universidade</a>
                        </div>
                        <div class="professor">
                            <h3>Práticas</h3>

                            {% for professor in cadeira.professor_pratica.all%}
                                <p>{{ professor }}</p>
                                <a href="{{ professor.linkedin }}" target="_blank" >Linkedin</a>
                                <a href="{{ professor.universidade }}" target="_blank">Universidade</a>
                            {% endfor %}
                        </div>
                        <br>
                    </div>
                    {% if cadeira.projetos is not Blank %}
                        {% for projeto in cadeira.projetos.all %}
                            {{projeto}}
                        {% endfor %}
                    {% endif %}

                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="educacao">

        <h2>Educação</h2>
        <div class="escolas">
            <ul>
                <li>Escola Secundária Alves Redol</li>
            </ul>
        </div>
    </div>

    <div class="interesses">
        <h2>Interesses e Hobbies</h2>
        <div>
            <ul>
                <li>
                    Voleibol 🏐
                </li>
            </ul>
        </div>
    </div>






{% endblock %}

portfolio/templates/portfolio/apresentacao.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Apresentação</h3>
    <p>texto texto texto texto texto texto texto </p>
{% endblock %}

portfolio/templates/portfolio/competencias.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Competências</h3>
    <p>texto texto texto texto texto texto texto </p>
{% endblock %}

portfolio/templates/portfolio/contact.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link href="{% static 'portfolio/css/styles_contact.css'  %}" rel="stylesheet" type="text/css">
    <br><br>
    <br><br>

    <div class="contact_div">
        <h2>Contact me</h2>
        <div class="grid_container">
            <div class="links_div">
                <a href="https://github.com/telmo-a22001972" target="_blank">
                    <img src="{% static 'portfolio/images/github_logo.gif' %}" alt="" class="socials_link">
                </a>
                <a href="https://www.linkedin.com/in/telmo-panaças/" target="_blank">
                    <img src="{% static 'portfolio/images/linked_in.gif' %}" alt="" class="socials_link">
                </a>
            </div>

            <div class="form_div">

                <form action="{% url 'portfolio:contact' %}" method="post">
                    {% csrf_token %}
                    <input type="text" placeholder="Your Name" required class="name" name="name">
                    <input type="email" placeholder="Your Email" required class="email" name="email">
                    <textarea placeholder="Message" required class="message" name="message"></textarea>
                    <input type="submit" value="Send">
                </form>
            </div>

        </div>

    </div>



{% endblock %}

portfolio/templates/portfolio/criar_cadeira.html
{% extends 'portfolio/layout.html' %}

{% block estilos %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/styles_criar_cadeira.css' %}">
{% endblock %}

{% block main %}
    <h1>Nova Cadeira</h1>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Post">
        </form>
    </div>
{% endblock %}

portfolio/templates/portfolio/criar_post.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link href="{% static 'portfolio/css/styles_criar_post.css'  %}" rel="stylesheet" type="text/css">
	<h1>Novo Post</h1>

    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Post">
        </form>

    </div>
{% endblock %}

portfolio/templates/portfolio/criar_tfc.html
{%  extends 'portfolio/layout.html' %}

{% block estilos %}
    {% load static %}
    <link href="{% static 'portfolio/css/styles_criar_tfc.css'  %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block main %}

	<h1>Novo TFC</h1>

    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Post">
        </form>
    </div>

{% endblock %}

portfolio/templates/portfolio/editar_post.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link href="{% static 'portfolio/css/styles_criar_post.css'  %}" rel="stylesheet" type="text/css">
	<h1>Novo Post</h1>

    <div class="container">
        <form action="{% url 'portfolio:editar_post' post_id %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Post">
        </form>
    </div>

{% endblock %}

portfolio/templates/portfolio/formacao.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Formação</h3>
    <p>texto texto texto texto texto texto texto </p>
{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link href="../../static/portfolio/css/styles_layout.css" rel="stylesheet" type="text/css">
    {% block script %}
    
    {% endblock %}

    {% block estilos %}

    {% endblock %}

</head>
<body>
    <header class="header">
        <div class="name_header">Telmo Panaças</div>
        {% if request.user.is_authenticated %}
            <nav class="navbar">
                <a href="{%  url 'portfolio:home' %}" class="button_home">home</a>
                <a href="{% url 'portfolio:about' %}" class="button_about">about</a>
                <a href="{% url 'portfolio:projetos' %}" class="button_projectos">projectos</a>
                <a href="{% url 'portfolio:posts' %}" class="button_blog">blog</a>
                <a href="{% url 'portfolio:web' %}" class="button_web">web</a>
                <a href="{% url 'portfolio:contact' %}" class="button_contact">contact</a>
                <a href="{% url 'portfolio:logout' %}" class="button_login" style="background-color: #F5D10D">logout</a>
            </nav>
        {% else %}
            <nav class="navbar">
                <a href="{%  url 'portfolio:home' %}" class="button_home">home</a>
                <a href="{% url 'portfolio:about' %}" class="button_about">about</a>
                <a href="{% url 'portfolio:projetos' %}" class="button_projectos">projectos</a>
                <a href="{% url 'portfolio:posts' %}" class="button_blog">blog</a>
                <a href="{% url 'portfolio:web' %}" class="button_web">web</a>
                <a href="{% url 'portfolio:contact' %}" class="button_contact">contact</a>
                <a href="{% url 'portfolio:login' %}" class="button_login">login</a>
            </nav>
        {% endif %}

    </header>

    <main>

        {% block main %}
	    {% endblock main %}

    </main>

    <article>
        {% block article %}
        {% endblock article %}
    </article>



</body>
<footer class="footer">
    <p>
        ULHT - 2022
    </p>
</footer>

</html>

portfolio/templates/portfolio/licenciatura.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link href="{% static 'portfolio/css/styles_licenciatura.css'  %}" rel="stylesheet" type="text/css">


    <div class="licenciatura_main">

        <div class="split-conteiner">

            <div class="info-side">
                <div>
                    <h2 class="titulo">Licenciatura</h2>

                </div>
                <br>
                <br>

                <div>
                    <h3>
                        Universidade Lusófona
                        <br>
                        de
                        <br>Humanidades e Tecnologias
                    </h3>
                </div>
                <br>
                <br>
                <div>
                    <h3>Engenharia Informática</h3>
                    <h5>2º Ano - 2º Semestre</h5>
                </div>
                <br>
                <br>
                <div>
                    {% load static %}
                    <img src="{% static 'portfolio/images/lusofona_logo_teste3.png' %}" class="lusofona_logo">
                </div>
            </div>

            <div class="cards-side">
                <div class="cards-conteiner">
                    <div class="card">
                        <h2>Matemática Discreta</h2>
                        <p>1º Ano - 1º Semestre</p>
                        <p>Nota: 20</p>
                        <p>Ranking 5/5 - ⭐⭐⭐⭐⭐</p>
                        <p>Professores</p>
                        <div class="professors_grid">
                            <div class="professor">
                                <h3>Teóricas</h3>
                                <p>Teresa Almada</p>
                                <a href="https://www.ulusofona.pt/docentes/teresa-maria-catanho-da-silva-almada" target="_blank">Lusófona</a>
                            </div>
                            <div class="professor">
                                <h3>Práticas</h3>
                                <p>Teresa Almada</p>
                                <a href="https://www.ulusofona.pt/docentes/teresa-maria-catanho-da-silva-almada" target="_blank">Lusófona</a>
                            </div>
                        </div>
                        <a class="link_disciplina" href="https://www.ulusofona.pt/licenciaturas/engenharia-informatica/matematica-discreta/ULHT260-1656" target="_blank">Ver mais</a>

                    </div>
                    <div class="card">
                        <h2>Álgebra Linear</h2>
                        <p>1º Ano - 2º Semestre</p>
                        <p>Nota: 17</p>
                        <p>Ranking 4/5 - ⭐⭐⭐⭐</p>
                        <p>Professores</p>
                        <div class="professors_grid">
                            <div class="professor">
                                <h3>Teóricas</h3>
                                <p>Teresa Almada</p>
                                <a href="https://www.ulusofona.pt/docentes/teresa-maria-catanho-da-silva-almada" target="_blank">Lusófona</a>
                            </div>
                            <div class="professor">
                                <h3>Práticas</h3>
                                <p>Anna Couto</p>
                                <a href="https://www.ulusofona.pt/teachers/anna-carolina-nametala-finamore-do-couto" target="_blank">Lusófona</a>
                                <a href="https://www.linkedin.com/in/anna-carolina-finamore-do-couto-aa7893114/" target="_blank">Linkedin</a>
                            </div>
                        </div>
                        <a class="link_disciplina" href="https://www.ulusofona.pt/licenciaturas/engenharia-informatica-redes-e-telecomunicacoes/algebra-linear/ULHT2531-2091" target="_blank">Ver mais</a>
                    </div>
                    <div class="card">
                        <h2>LP2</h2>
                        <p>2º Ano - 1º Semestre</p>
                        <p>Nota: 16</p>
                        <p>Ranking 4/5 - ⭐⭐⭐⭐</p>
                        <p>Professores</p>
                        <div class="professors_grid">
                            <div class="professor">
                                <h3>Teóricas</h3>
                                <p>Pedro Alves</p>
                                <a href="https://www.ulusofona.pt/docentes/pedro-hugo-de-queiros-alves" target="_blank">Lusófona</a>
                                <a href="https://www.linkedin.com/in/palves/?originalSubdomain=pt" target="_blank">Linkedin</a>
                            </div>
                            <div class="professor">
                                <h3>Práticas</h3>
                                <p>Bruno Cipriano</p>
                                <a href="https://www.ulusofona.pt/docentes/bruno-miguel-pereira-cipriano" target="_blank">Lusófona</a>
                                <a href="https://www.linkedin.com/in/bruno-cipriano-1a49624/" target="_blank">Linkedin</a>
                            </div>
                        </div>
                        <a class="link_disciplina" href="https://www.ulusofona.pt/licenciaturas/engenharia-informatica/linguagens-de-programacao-ii/ULHT260-898" target="_blank">Ver mais</a>

                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock main %}

portfolio/templates/portfolio/posts.html
{%  extends 'portfolio/layout.html' %}

{% block estilos %}
    {% load static %}
    <link href="{% static 'portfolio/css/styles_posts.css'  %}" rel="stylesheet" type="text/css">
{% endblock estilos %}

{% block main %}

	<h1>Blog</h1>

    <div class="btn_div">
        <a href="{% url 'portfolio:criar_post' %}" class="btn">+ Novo Post</a>
    </div>

    <div class="posts_container">

        {% for post in posts %}
            <div class="blog_post">
                <a href="{% url 'portfolio:editar_post' post.id %}" class="btn_editar">Editar</a>
                <h2>{{post.titulo}}</h2>
                <br>
                <br>
                <p>{{post.descricao}}</p>
                <br>
                <br>
                <br>
                <div class="post_criacao">
                    <p>Criado: {{post.criacao.day}}/{{post.criacao.month}}/{{post.criacao.year}} </p>
                </div>
                <div class="post_autor">
                    <p>Autor: {{ post.autor }}</p>
                </div>
            </div>
            <div class="comentarios_div">
                <h2>Comentários</h2>
                <br>

                {% if not post.coments.all %}
                    Sem comentários... <a href="{% url 'portfolio:criar_comentario'%}" style="color: white;">Comentar</a>
                {% else %}
                    <a href="{% url 'portfolio:criar_comentario'%}" style="color: white;">Comentar</a>
                    <br><br>
                    {% for comentario in post.coments.all %}
                        <strong>
                            {{ comentario.autor }} - {{ comentario.criacao_data }}
                        </strong>
                        <br>
                        {{ comentario.conteudo }}
                        <br>
                        <br>

                    {% endfor %}

                {% endif %}
                </div>

        {% endfor %}

    </div>

{% endblock %}

portfolio/templates/portfolio/projetos.html
{%  extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link href="{% static 'portfolio/css/styles_projetos.css'  %}" rel="stylesheet" type="text/css">

    <div class="projetos_main">
        <div class="titulo_div">
            <h1>Projetos</h1>
        </div>

        <div class="cards-conteiner">
            <div class="card">
                <h2>SOVAC</h2>
                <div>
                    <p class="descricao">
                        O objetivo geral do projeto será simular um
                        sistema de pedidos e respostas genérico, com três tipos de participantes diferentes: clientes,
                        proxies e servidores. Esta aplicação, chamada SOVAC, simula o processo de aquisição e
                        distribuição de vacinas, onde os clientes são as instalações de saúde e farmacêuticas, os proxies são os serviços de distribuição,
                        e os servidores são os laboratórios farmacêuticos que produzem e
                        fornecem as vacinas.
                    </p>
                </div>
                <p>Realizado em: 2021</p>
                <p>Cadeira: Sistemas Operativos</p>
                <div>
                    <p>
                        Participantes:
                    </p>
                    <a class="link_linkedin" href="https://www.linkedin.com/in/bernardobaltazar/" target="_blank">Bernardo Baltazar</a>
                </div>
            </div>
        </div>
    </div>
    <div class="TFCS_div">

        <div class="titulo_div" style="padding-top: 70px">
            <h1>TFCs DEISI</h1>
        </div>
        <br><br>
        {% if request.user.is_authenticated %}
            <div class="btn_div">
                <a href="{% url 'portfolio:criar_tfc' %}" class="btn">+ Novo TFC</a>
            </div>
        {% endif %}

        <div class="cards-conteiner">

            {% for tfc in tfcs %}
                <div class="tfc_card">
                    <h2>{{ tfc.titulo }}</h2>
                    <br>
                    <div style="text-align: justify">
                        <p style="white-space: pre-wrap;">{{ tfc.resumo}}</p>
                    </div>

                    <br>
                    <br>
                    <div class="grid_conteiner">
                        <div class="grid_1">

                            <p>Realizado por:</p>
                            {% for autor in tfc.autores.all %}
                                <li>{{ autor }}</li>
                            {% endfor %}
                            <br>
                            <p>Orientadores:</p>
                            {% for orientador in tfc.orientadores.all %}
                                <li>{{ orientador }}</li>
                            {% endfor %}

                        </div>

                        <div class="grid_2">
                            <p>Ano de realização: {{ tfc.ano }}</p>
                            <br>
                            <a href="{{ tfc.github_link }}" target="_blank" class="link_linkedin">GitHub</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>

    </div>



{% endblock %}